### ISSUE TITLE
BOM?

### ISSUE THREAD

**Issue by hexbus** [jcs/WiFiStation#2]
Greetings, I know you've been out of these for a while.  Can you please put a basic BOM, including any part numbers (if you have them) on the repo?  I'd like to make myself one.  Thanks!

So far, to get started, I've found the following:

- https://www.digikey.com/en/products/detail/microchip-technology/MCP23S18-E-SP/1994655 (MCP23S18)
- https://www.adafruit.com/product/3046 (Assembled Header Huzzah)
- https://www.digikey.com/en/products/detail/te-connectivity-amp-connectors/1-2199298-9/5022045 (28 pin .3 socket)

Still need to locate the proper:

- DB25 connector with proper outline
- 12 pin header (female - pitch?)
- 16 pin header (female - pitch?)
- 4.7k ohm resistor array (is this it?  https://www.digikey.com/en/products/detail/bourns-inc/4611X-101-472LF/3741135 )

Thanks again!  Can't wait to try to get the parts and PCB to try this out.

**Comment by jcs** [comment]
Sure, here's an Octopart BOM: https://octopart.com/bom-tool/1wY3fCEg
